# Generated by Django 4.0.1 on 2022-02-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_rename_gamerating_rating_rename_gamereview_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecategory',
            name='user',
        ),
    ]
