# Generated by Django 4.0.1 on 2022-02-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0004_game_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='raterapi.game'),
        ),
    ]
